<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alligator.Solver\Alligator.Solver.csproj" />
    <ProjectReference Include="..\Alligator.TicTacToe\Alligator.TicTacToe.csproj" />
  </ItemGroup>

</Project>
